spring:
  data:
    mongodb:
      username: ousmane
      password: ousmane
      host: localhost
      port: 27017
      database: users
      authentication-database: admin
  application:
    name: keycloak-auth
    config:
      listings-url: http://localhost:6801/api/listings

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9099/realms/connectTroc"


server:
  port: 6700
  servlet:
    context-path: /auth

