spring:
  data:
    mongodb:
      username: ousmane
      password: ousmane
      host: localhost
      port: 27017
      database: listings
      authentication-database: admin
  application:
    name: listing-service
    config:
      users-url: http://localhost:6700/auth/internal-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9099/realms/connectTroc"


server:
  port: 6801