spring:
  application:
    name: listing-service
    config:
      users-url: http://localhost:6700/auth/internal-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9099/realms/connectTroc"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2

server:
  port: 6801